from pathlib import Path

SOURCE_PATH = Path(__file__).parent
RESOURCE_PATH = SOURCE_PATH/'resources'
BPMN_DIR_PATH = RESOURCE_PATH/'bpmns'
CASE_TABLE_DIR_PATH = RESOURCE_PATH/'case_tables'
CSV_LOGS_DIR_PATH = RESOURCE_PATH/'csv_logs'
SIMULATION_DATA_DIR_PATH = RESOURCE_PATH/'simulation_data'
XES_LOGS_DIR_PATH = RESOURCE_PATH/'xes_logs'